### ISSUE TITLE
Filter classes for personalized calendar

### ISSUE THREAD

**Issue by giorgosioak** [giorgosioak/schedule_csd#2]
Each user can create a list of classes for a personalized calendar.

`Expected features:`
- checkbox ( check = show, not check = hide )
- no classes chosen = show all classes
- use of local storage
- edit button

`Optional features:`
- clear button to remove classes
- save button ( one use of local storage ) instead of live-saving ( multiple calls of local storage )

**Comment by tzagkaris** [comment]
Great. 
Will work on it.
