### ISSUE TITLE
[BUG] Show/Hide Classes misbehavior

### ISSUE THREAD

**Issue by giorgosioak** [giorgosioak/schedule_csd#7]
I have some suggestions for fixing this misbehavior.

1. Change `Show/Hide Classes` to `Manage Classes`
2. On click Manage, save `Show/Hide pinned` state and restore its value in the end
3. This could be easier if we had a `Save` at the end instead of saving directly ( Manage button replaced with Save (maybe) )

**Comment by tzagkaris** [comment]
ok, will look at it over the weekend
